### ISSUE TITLE
Strict limit of unit test

### ISSUE THREAD

**Issue by sukrosono** [dakolech/angular-unit-testing-helpers#1]
You are awesome man, this will help alot

[have you read this](http://www.yearofmoo.com/2013/01/full-spectrum-testing-with-angularjs-and-karma.html)

But i wonder **what should be better not in unit test**?
my controller is quite complex and and more details we test in unit test, later if the app grow it will force us to change 2 code right?

**Comment by dakolech** [comment]
In my opinion, the more tests the better. Unit testing is a great tool for documentation of code. With tests, you are describing all methods and functions.

If your controller is complex, then you are doing something wrong. I think that in AngularJS controllers should be slim as possible. All logic should be in services. And of course not in one. You should split your code into small, independent units. So when the code will change, then you will have to change only small pieces of tests.

I've never heard about ngMidwayTester, but it looks good. In my opinion, there should be also some integration tests in every project, to test how some services are interacting with each others. This tool is really helpful. Maybe in near future, I will add some features to making integration tests easier.

**Comment by sukrosono** [comment]
@dakolech my controller involving ui-router and ui-grid, any advice?
I already move some of it into service.

**Comment by dakolech** [comment]
I'm also using ui-grid and ui-router in my actual project. I moved as much as possible to services and I'm testing only my code, not ui-router or ui-grid implementation. To ui-grid there are great tools for E2E tests.

**Comment by sukrosono** [comment]
@dakolech did you mind show me an example for that?

**Comment by dakolech** [comment]
Unfortunately I can't, it's a private project.

**Comment by sukrosono** [comment]
@dakolech I mean just the simple way, not exact code.
I can't figure it out how to move some code which involve ui-grid from controller to service.
But it's okay, i know you responsible for that.

**Comment by dakolech** [comment]
I've moved all tableOptions to the service and when the controller is fired I'm calling a method from there.
There is another service for searching (SearchProductsService): 

```
registerGridOptions() {
    let singleFilter = (renderableRows) => {
        var searchResults = this.SearchProductsService.search(this.searchText, renderableRows);
        return searchResults;
    };
    this.gridOptions.onRegisterApi = (gridApi) => {
        let priority = 200;
        this.gridApi = gridApi;
        this.gridApi.grid.registerRowsProcessor(singleFilter, priority);
    };

    this.gridOptions.appScopeProvider = this;
}
```

I know, that some code must stay in the controller, but in this example, I'm using the search method from the `SearchProductsService` in `registerRowsProcessor`.
